#!/usr/bin/env python3
"""
deploy_model.py
Model deployment workflow: convert trained model to TFLite, generate C header, and copy to firmware.
"""

import os
import subprocess
import sys
from pathlib import Path

# Paths
PROJECT_ROOT = Path(__file__).parent.parent
MODEL_DIR = PROJECT_ROOT / "ai"
FIRMWARE_DIR = PROJECT_ROOT / "firmware"
TFLITE_PATH = MODEL_DIR / "model.tflite"
HEADER_PATH = FIRMWARE_DIR / "model_data.h"

def convert_to_tflite(keras_path: Path = None, quantize: bool = True) -> Path:
    """
    Convert a trained Keras model to TFLite.
    If keras_path is None, expects existing model.tflite.
    """
    if keras_path:
        import tensorflow as tf
        model = tf.keras.models.load_model(keras_path)
        converter = tf.lite.TFLiteConverter.from_keras_model(model)
        if quantize:
            converter.optimizations = [tf.lite.Optimize.DEFAULT]
            converter.target_spec.supported_types = [tf.float16]  # or uint8
        tflite_model = converter.convert()
        with open(TFLITE_PATH, "wb") as f:
            f.write(tflite_model)
        print(f"Converted {keras_path} to {TFLITE_PATH}")
    else:
        if not TFLITE_PATH.exists():
            raise FileNotFoundError(f"TFLite model not found at {TFLITE_PATH}")
        print(f"Using existing TFLite model at {TFLITE_PATH}")
    return TFLITE_PATH

def generate_c_header(tflite_path: Path, header_path: Path) -> None:
    """
    Convert TFLite binary to a C header without requiring xxd.
    """
    if not tflite_path.exists():
        raise FileNotFoundError(f"TFLite model not found: {tflite_path}")
    # Ensure firmware directory exists
    header_path.parent.mkdir(parents=True, exist_ok=True)
    # Read binary data
    with open(tflite_path, "rb") as f:
        data = f.read()
    # Write as C array
    with open(header_path, "w") as f:
        f.write("// Generated by deploy_model.py\n")
        f.write("const unsigned char g_model_data[] = {\n")
        for i, b in enumerate(data):
            f.write(f"0x{b:02X}")
            if i < len(data) - 1:
                f.write(", ")
            if (i + 1) % 16 == 0:
                f.write("\n")
        f.write("\n};\n")
        f.write(f"const int g_model_data_len = {len(data)};\n")
    print(f"Generated C header at {header_path}")

def verify_model(tflite_path: Path) -> None:
    """
    Quick verification: load model with TFLite Interpreter and print input/output details.
    """
    import tensorflow as tf
    interpreter = tf.lite.Interpreter(model_path=str(tflite_path))
    interpreter.allocate_tensors()
    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()
    print("Model verification:")
    print("  Input:", input_details)
    print("  Output:", output_details)

def deploy(keras_path: Path = None, quantize: bool = True) -> None:
    """
    Full deployment pipeline: convert -> generate header -> verify.
    """
    print("=== Deploying model ===")
    tflite_path = convert_to_tflite(keras_path, quantize)
    generate_c_header(tflite_path, HEADER_PATH)
    verify_model(tflite_path)
    print("=== Deployment complete ===")
    print(f"  TFLite: {tflite_path}")
    print(f"  Header: {HEADER_PATH}")
    print("  Ready to compile firmware.ino")

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Deploy trained model to ESP32 firmware")
    parser.add_argument("--keras", type=Path, help="Path to trained .h5/.keras model (optional)")
    parser.add_argument("--no-quantize", action="store_true", help="Skip quantization")
    args = parser.parse_args()
    deploy(keras_path=args.keras, quantize=not args.no_quantize)
